using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace StoreManager.UserControls
{
    /// <summary>
    /// Interaction logic for ProductView.xaml
    /// </summary>
    public partial class ProductView : UserControl
    {
        public ProductView()
        {
            InitializeComponent();
        }

        /// <summary>
        /// This method is normally generated by the XAML designer.
        /// If your .xaml file is missing or not set to compile as a Page/UserControl,
        /// the InitializeComponent method will not be generated.
        /// </summary>
        private void InitializeComponent()
        {
            System.Uri resourceLocater = new System.Uri("/StoreManager;component/UserControls/ProductView.xaml", System.UriKind.Relative);
            System.Windows.Application.LoadComponent(this, resourceLocater);
        }
    }
}
